microsoft/PowerApps-Tooling

src/PAModel/IR/UniqueIdRestorer.cs

Fix Unique ID collision on control add

---

src/PAModel/IR/IRNode.cs
src/PAModel/PAConvert/ErrorCode.cs
src/PAModel/PAConvert/Parser/Parser.cs
src/PAModel/PAConvert/Parser/SourceLocation.cs
src/PAModel/PAConvert/Yaml/YamlLexer.cs
src/PAModelTests/YamlTest.cs

Yaml fixes

---

src/PAModel/EditorState/ControlState.cs
src/PAModel/Entropy.cs
src/PAModel/IR/IRStateHelpers.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/SourceTransforms/GroupControlTransform.cs

Move PublishOrderIndex to Entropy

---

src/PAModel/CanvasDocument.cs
src/PAModel/Entropy.cs
src/PAModel/MsAppTest.cs
src/PAModel/Schemas/adhoc/AppCheckerResultJson.cs
src/PAModel/Serializers/FileEntry.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs

Move Sarif file and other deletables to Entropy/, and Themes to src/

---

src/PAModel/CanvasDocument.cs
src/PAModel/MsAppTest.cs
src/PAModel/PAConvert/ErrorCode.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModelTests/ErrorTests.cs

add stream overload.

---

src/PAModel/ControlTemplates/DynamicProperties.cs
src/PAModel/IR/IRStateHelpers.cs
src/PAModel/Serializers/DefaultRuleHelper.cs
src/PAModel/SourceTransforms/DefaultValuesTransform.cs
src/PAModel/SourceTransforms/SourceTransformer.cs
src/PAModelTests/SrcBaseline/AutoLayout_test.pa.yaml

Add default value handling for responsive properties

---

azure-pipelines.yml
src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj
src/PAModel/Schemas/BuildVerJson.cs
src/PAModel/Schemas/adhoc/ChecksumJson.cs
src/PAModel/Serializers/SourceSerializer.cs
targets/Program.cs

Stamp git hash and local build in Checksum.json

---

src/PAModel/Utility/Utility.cs
src/PAModelTests/UtilityTests.cs

Fix relative path logic

---

src/PAModel/ControlTemplates/ControlTemplate.cs
src/PAModel/ControlTemplates/GlobalTemplates.cs
src/PAModel/Serializers/DefaultRuleHelper.cs
src/PAModel/SourceTransforms/DefaultValuesTransform.cs
src/PAModelTests/SrcBaseline/AutoLayout_test.pa.yaml

Add variant support for default properties, and add group container template

---

src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/Utility/Utility.cs
src/PAModelTests/UtilityTests.cs

Double unescaping.

---

src/PAModel/CanvasDocument.cs
src/PAModel/Utility/Utility.cs
src/PASopa/Program.cs

Convert to full paths.

---

azure-pipelines.yml
src/PASopa/PASopa.csproj
targets/targets.csproj

Fix ADO build failures due to localbuild stamping

---

src/PAModel/Checksum/ChecksumMaker.cs
src/PAModel/Checksum/IHashMaker.cs
src/PAModel/MsAppTest.cs
src/PAModel/Serializers/SourceSerializer.cs

No change to actual hash algorithm.

better hash diagnostics.

---

src/PAModel/PAConvert/PAWriterVisitor.cs
src/PAModelTests/SrcBaseline/AutoLayout_test.pa.yaml
src/PAModelTests/SrcBaseline/ComponentFunction_Test.pa.yaml
src/PAModelTests/SrcBaseline/Gallery_ScreenTest.pa.yaml
src/PAModelTests/SrcBaseline/GroupControl_Test.pa.yaml
src/PAModelTests/SrcBaseline/TestStudio_Test.pa.yaml
src/PAModelTests/SrcBaseline/Weather_Screen1.pa.yaml

Fix #166
Since we can read any order, this is not a breaking change, so we don't need to update the source format.

Make deterministic ordering

---

src/PAModel/EditorState/CombinedTemplateState.cs
src/PAModel/Schemas/adhoc/TemplateMetadataJson.cs
src/PAModel/Serializers/MsAppSerializer.cs

Fix ComponentDescription metadata roundtrip

---

src/PAModel/Serializers/MsAppSerializer.cs

Allow checksum.json to be missing

---

src/PAModel/Checksum/ChecksumMaker.cs
src/PAModel/Checksum/IHashMaker.cs
src/PAModel/Entropy.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModelTests/ChecksumTests.cs

Better variance and avoids a bunch of collisions.

New checksum.

---

src/PAModel/PAConvert/Yaml/YamlWriter.cs
src/PAModelTests/YamlTest.cs

Write property values in .fx.yaml with platform-appropriate newlines

---

src/PAModel/CanvasDocument.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/Themes/Theme.cs

Only load theme that matches the provided theme name

---

src/PAModel/CanvasDocument.cs
src/PAModel/Schemas/adhoc/AppInsightsKey.cs
src/PAModel/Serializers/FileEntry.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs

Changes to abstract out InstumentationKey from Porperties.json to a separate file - ApplicationInsightsKey.json

Changes to abstract out InstumentationKey from Properties.json to a separate file

---

src/PAModel/EditorState/CombinedTemplateState.cs
src/PAModel/PAConvert/ErrorCode.cs
src/PAModel/PAConvert/PAConstants.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs

Adding validation to check for the existence of the templates which are referred in the sources.
* Added validation for widget templates
* Added validation for component templates
* Added validation for PCF templates
The validation would not fail for widget templates for existing unpacked sources.

#215: Adding validation to check for the existence of the templates 

---

src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/SourceTransforms/AppTestTransform.cs
src/PAModelTests/SourceDecoderTests.cs
src/PAModelTests/SrcBaseline/TestStudio_Test.fx.yaml

Made changes to shard AppTest control into individual test files for every test suite.

#228 Changes to Shard AppTest into individual files

---

src/PAModel/CanvasDocument.cs
src/PASopa/Program.cs

Made Changes to throw unhandled exceptions to the caller when intended.

Changes to throw unhandled exceptions to the caller

---

src/PAModel/Entropy.cs
src/PAModel/Schemas/DocumentPropertiesJson.cs

Changes to move ErrorCount property from Properties.json to Entropy

#227 : Moving ErrorCount property to entropy

---

src/PAModel/CanvasDocument.cs
src/PAModel/PAConvert/ErrorCode.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/Utility/Utilities.cs
src/PAModelTests/ErrorTests.cs

Fix #238 - better handling of user errors.

---

src/PAModel/CanvasDocument.cs
src/PAModel/Checksum/ChecksumMaker.cs
src/PAModel/EditorState/CombinedTemplateState.cs
src/PAModel/Schemas/PcfControls/AuthConfigProperty.cs
src/PAModel/Schemas/PcfControls/DataConnectorMetadata.cs
src/PAModel/Schemas/PcfControls/EnumValues.cs
src/PAModel/Schemas/PcfControls/Event.cs
src/PAModel/Schemas/PcfControls/PcfControl.cs
src/PAModel/Schemas/PcfControls/PcfControlDoublyEncoded.cs
src/PAModel/Schemas/PcfControls/PorpertyDependency.cs
src/PAModel/Schemas/PcfControls/Property.cs
src/PAModel/Schemas/PcfControls/Resource.cs
src/PAModel/Schemas/adhoc/Control.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModelTests/ChecksumTests.cs

* Pcf control templates sharding
* Checksum update

PCF control template sharding to pkgs/PcfControlTemplates directory

---

azure-pipelines.yml

Whoops, accidentally pushed an invalid job name here. Fixes that.

Update job name

---

src/PAModel/PAConvert/Yaml/YamlConverter.cs
src/PAModel/PAConvert/Yaml/YamlLexer.cs
src/PAModelTests/PublicSurfaceTests.cs
src/PAModelTests/YamlTest.cs

Doesn't yet expose full lexer - wrap it in a dictionary converter for convenience.

Make basic yaml reader/write public.

---

README.md

Adding latest version of PAC CLI to readme. Fixes #283.

Adding latest version PAC CLI to readme.md

---

src/PAModel/IR/IRNode.cs
src/PAModel/MergeTool/ControlDiffVisitor.cs
src/PAModel/MergeTool/Deltas/ChangeComponentFunction.cs
src/PAModel/MergeTool/Deltas/ChangeProperty.cs
src/PAModel/MergeTool/Diff.cs

Add SmartMerge support for Component Custom Properties

---

README.md

Update README.md for pa.yaml to fx.yaml

---

src/PAModel/CanvasDocument.cs

Fixes a smart merge issue with PCF conflicts

Clone PCF templates

---

src/PAModel/CanvasDocument.cs
src/PAModel/Checksum/IHashMaker.cs
src/PAModel/MsAppTest.cs
src/PAModelTests/NameCollisionTests.cs
src/PAModelTests/RoundtripTests.cs
src/PASopa/Program.cs

Fix some real cloning bugs - fields weren't getting copied over for a clone.

Add stress tests for smart merge 

---

.github/ISSUE_TEMPLATE/bug-report.md

Making bug reporting easier by creating an issue template.
A new issue created with this template will look like this -

Bug Report Template

---

.gitignore
README.md
docs/KnownIssues.md

Added Known Issues document, associated with two of the issues recently discovered. The issues listed are final, however the language, descriptions are work in progress. Will be finalized based on feedback.

Added KnownIssues document

---

src/PAModel/PAConvert/Yaml/YamlLexer.cs

Created to modify the error message being printed by checkDuplicate.

Modify checkDuplicate error message

---

src/PAModelTests/PAModelTests.csproj

PALT - Component Governance - Newtonsoft 9.0.1
Update Newtonsoft 9.0.1 to 13.0.1
Ran the build locally (version updated locally)

Handling Newtonsoft Component Governance

---

.github/ISSUE_TEMPLATE/bug-report.md

Hard to tell what was added since last triage
Adding "new" label to created bugs to allow easy querying
- Updated bug template to include "new" label
- Compared to one in PowerApps-TestEngine which works fine. Will test after merged

Update bug template to include "new" label

---

src/PAModel/EditorState/CombinedTemplateState.cs
src/PAModel/IR/IRStateHelpers.cs
src/PAModel/Serializers/TransformLogo.cs

AzDo issue: 3423142
NullRef exceptions

Fixed multiple NullRefs

---

azure-pipelines.yml

Generating SBOM file for compliance purposes.

SBOM Generator

---

.github/workflows/CI.yml
azure-pipelines.yml

This PR adds CodeQL tasks to the build pipelines in this repo.
- [N/A] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [N/A] My changes generate no new warnings

Added CodeQL Tasks to Build Pipelines

---

src/PAModel/PAConvert/Yaml/Attributes/YamlObject.cs
src/PAModel/PAConvert/Yaml/Attributes/YamlProperty.cs
src/PAModel/PAConvert/Yaml/YamlLexer.cs
src/PAModel/PAConvert/Yaml/YamlLexerOptions.cs
src/PAModel/PAConvert/Yaml/YamlParseException.cs
src/PAModel/PAConvert/Yaml/YamlPocoDeserializer.cs
src/PAModel/PAConvert/Yaml/YamlPocoSerializer.cs
src/PAModel/PAConvert/Yaml/YamlWriter.cs
src/PAModelTests/YamlSerializerTests/InvalidObject.cs
src/PAModelTests/YamlSerializerTests/SimpleObject.cs
src/PAModelTests/YamlSerializerTests/YamlSerializerTests.cs

New Yaml attributes for serialization/deserialization

Yaml attributes

---

.github/workflows/CI.yml
.vscode/launch.json

Removing remaining dotnet 3.1 references

Clean up remaining netcoreapp3.1 references

---

azure-pipelines.yml

@mizrael I am reverting some of tasks you added

Removed unnecessary tasks

---

src/Microsoft.PowerPlatform.PowerApps.Persistence.Tests/Yaml/YamlDeserializerTests.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence.Tests/Yaml/YamlSerializerTests.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/BuiltInTemplatesUris.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/Text.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Yaml/ControlPropertiesCollectionConverter.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Yaml/SerializerBuilderExtensions.cs

serializing control properties in alphabetical order
Unit tests

serializing control properties in alphabetical order

---

src/Persistence/Yaml/ControlPropertiesCollectionConverter.cs
src/Persistence/Yaml/YamlDeserializerOptions.cs
src/Persistence/Yaml/YamlSerializationFactory.cs
src/Persistence/Yaml/YamlSerializerOptions.cs

minor refactoring

---

src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/Yaml/ValidSerializerTests.cs
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl7.yaml
src/Persistence.Tests/_TestData/ValidYaml/Strings.fx.yaml
src/Persistence/Models/ControlPropertyValue.cs
src/Persistence/Yaml/ControlPropertiesCollectionConverter.cs

- Changed null to empty string
- More tests for string serialization

Changed null to empty string

---

.github/workflows/CI.yml
samples/MSAppGenerator/AppGeneratorFactory.cs
samples/MSAppGenerator/ExampleGenerator.cs
samples/MSAppGenerator/IAppGenerator.cs
samples/MSAppGenerator/IAppGeneratorFactory.cs
samples/MSAppGenerator/InteractiveGenerator.cs
samples/MSAppGenerator/MSAppGenerator.csproj
samples/Test.AppWriter/Program.cs
samples/Test.AppWriter/Test.AppWriter.csproj
samples/samples.sln
src/Persistence.Tests/MsApp/MsappArchiveTests.cs
src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/Yaml/ValidSerializerTests.cs
src/Persistence.Tests/_TestData/ValidYaml/App-with-settings.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Components/CustomProperty1.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Components/CustomProperty2.pa.yaml
src/Persistence/Models/App.cs
src/Persistence/Models/Component.cs
src/Persistence/Models/CustomProperty.cs
src/Persistence/Models/CustomPropertyParameter.cs
src/Persistence/Models/Header.cs
src/Persistence/Models/Settings.cs
src/Persistence/MsApp/IMsappArchive.cs
src/Persistence/MsApp/MsappArchive.cs
src/Persistence/Yaml/FirstClassControlsEmitter.cs
src/Persistence/Yaml/NamedObjectEmitter.cs

- Moved App Generator code to shared library for access from other sample app and separation of responsibility
- Refactored App Generator code to include factory pattern for different generator implementations

Moved AppGenerator to shared library and refactored Generator code

---

src/Persistence.Tests/Extensions/IYamlDeserializerExtensions.cs
src/Persistence.Tests/Yaml/DeserializerInvalidTests.cs
src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/Yaml/RoundTripTests.cs
src/Persistence.Tests/Yaml/ValidSerializerTests.cs
src/Persistence.Tests/Yaml/ZIndexOrderingTests.cs
src/Persistence/MsApp/MsappArchive.cs
src/Persistence/Yaml/IYamlDeserializer.cs
src/Persistence/Yaml/IYamlSerializer.cs
src/Persistence/Yaml/YamlDeserializer.cs
src/Persistence/Yaml/YamlSerializer.cs

Renaming from PR feedback on #606 post merge

Yaml Serializer cleanup and tests

---

src/Persistence.Tests/Yaml/ValidSerializerTests.cs
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl/with-layout.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl/with-variant.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl1.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl2.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl3.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl4.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl5.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl6.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl7.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/BuiltInControl8.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Components/CustomProperty1.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Components/CustomProperty2.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Group/with-nested-children.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Group/with-two-children.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen-with-control1.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen-with-controls-as-temples.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen-with-controls.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen/with-gallery.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen/with-properties-and-controls.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen/with-properties-and-nested-controls.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Strings.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/With-list-of-controls.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/ZIndexOrdering/Screen-with-sorted-children.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/ZIndexOrdering/With-list-of-controls-with-children.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/ZIndexOrdering/With-list-of-controls.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/ZIndexOrdering/With-sortedlist-of-controls.pa.yaml
src/Persistence/Yaml/FirstClassControlsEmitter.cs

Updating control output, pattern `Label: ` -> `Control: Label`,  to better match the end goal schema

Control types outputted with `Control: [TemplateName]`

---

src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/Yaml/ValidSerializerTests.cs
src/Persistence.Tests/_TestData/ValidYaml-CI/CommandComponent.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml-CI/Component.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/CommandComponent.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Component.pa.yaml
src/Persistence/Models/Component.cs
src/Persistence/Models/CustomProperty.cs
src/Persistence/Yaml/ComponentConverter.cs

- added `Description` and `AccessAppScope` to Component Definitions
- removed `ToolTip` property from Custom Properties

updated Component Definitions

---

samples/MSAppGenerator/AppCreator.cs
samples/MSAppGenerator/AppGeneratorFactory.cs
samples/MSAppGenerator/ExampleGenerator.cs
samples/MSAppGenerator/IAppGenerator.cs
samples/MSAppGenerator/InteractiveGenerator.cs
src/Persistence.Tests/MsApp/MsappArchiveSaveTests.cs
src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/Yaml/ValidSerializerTests.cs
src/Persistence.Tests/_TestData/ValidYaml-CI/App.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/App.pa.yaml
src/Persistence/Models/App.cs
src/Persistence/Models/AppProperties.cs
src/Persistence/Models/DataSources.cs
src/Persistence/Models/Header.cs
src/Persistence/MsApp/IMsappArchive.cs
src/Persistence/MsApp/IMsappArchiveFactory.cs
src/Persistence/MsApp/MsappArchive.cs
src/Persistence/MsApp/MsappArchiveFactory.cs
src/Persistence/Templates/ControlFactory.cs
src/Persistence/Templates/IControlFactory.cs

Added DataSources and default App Properties

Added DataSources and default App Properties

---

docs/pa.yaml-schema.json

This is to enable simple validation for VSCode and will be expanded and refined.

Yaml RedHat extension schema

---

samples/README.md

n/a
n/a
- Updating the samples project readme to add 'getting started' section and some other info
n/a

Updates to the samples project ReadMe

---

.github/CODEOWNERS

Update CODEOWNERS to add @microsoft/powerapps-tools-contrib to owners list of all the files outside of docs/samples/src directories

Update CODEOWNERS to add @microsoft/powerapps-tools-contrib to owners list of all the files outside of docs/samples/src directories

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj
src/PAModel/packages.lock.json
src/Persistence/PaYaml/Models/SchemaV3/ControlInstance.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/Screens/FormsScreen2.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

Certain controls show up as locked in the Studio. We need to serilaize Locked with YAML code to implement this feature.

serialize Locked

---

src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj
src/PAModel/packages.lock.json

Downgrade system text json version to 8.0.5 since there was a version conflict between the version used by DocServer

Downgrade system text json version

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence/PaYaml/Models/SchemaV3/ComponentDefinition.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/Components/MyComponentLibrary.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

- Updated schema
- Added examples and tests.

Support CommandComponent definitions
