src/PAModel/IR/IRStateHelpers.cs
src/PAModelTests/SrcBaseline/ComponentFunction_Test.pa.yaml

fixes #117 
This updates our control ordering to (mostly) match what authors see in Studio's tree view

Order children by ZIndex

---

targets/Program.cs

Partial fix for #124, we still have a number of test failures on linux that need to be addressed before we're truly cross-platform.

Fix capitalization of Pasopa in build script

---

src/PAModel/EditorState/CombinedTemplateState.cs
src/PAModel/Entropy.cs
src/PAModel/IR/IRStateHelpers.cs
src/PAModel/Schemas/adhoc/Control.cs
src/PAModel/Serializers/MsAppSerializer.cs

The CustomControlJson can vary slightly between columns for the legacy data table control. However, it's safe to just pick any individual json and use it for all the columns.
fixes #120

Fix roundtrip failures for Legacy DataTable Control

---

src/PAModel/Serializers/SourceSerializer.cs

Some datasources (like AIBuilder) don't have a wadl/swagger file.

---

global.json

Else it will pick a random / latest version and can get build errors depending on what's installed.

Add global.json to get dotnet tooling to lock into right version.

---

src/PAModel/Serializers/FileEntry.cs
src/PAModel/Utility/DirectoryHelper.cs
src/PAModel/Utility/Utilities.cs
src/PAModelTests/UtilityTests.cs

Thanks to @StevenRasmussen  for reporting and submitting ideas at, https://github.com/microsoft/PowerApps-Language-Tooling/issues/202, 
- also reenables some tests that were accidentally removed

Fix issue in GetRelativePath() when directory has a dot.

---

src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/SourceTransforms/ComponentDefinitionTransform.cs

Made the changes to handle for empty LocalDatabaseReferences property in proerties.json when the app has default cds as data source. This is happening for command components.
Also in certain cases the data source in table definition is null which causes failure during round trip, added fix for that as well.

Handling for empty LocalDatabaseReferences which has valid CDS datasource

---

src/PAModel/IR/IRStateHelpers.cs
src/PAModel/SourceTransforms/DefaultValuesTransform.cs
src/PAModel/SourceTransforms/GroupControlTransform.cs
src/PAModelTests/GroupControlRecreationTest.cs

Fixes #209 
In the control .json file, group controls must be ordered after the controls they are grouping of, to ensure that they are reparented correctly when loading.

Ensure group controls with missing editor state load correctly in Studio

---

src/PAModel/IR/IRStateHelpers.cs
src/PAModel/PAConvert/ErrorCode.cs
src/PAModel/Serializers/SourceSerializer.cs

Adding a new error code for scenarios which are not supported by the tool.
Eg: "Connection Accounts is using the old CDS connector which is incompatible with this tool"

#211: adding new error type for unsupported scenarios.

---

src/PAModel/CanvasDocument.cs
src/PAModel/Entropy.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/TransformResourceJson.cs
src/PAModelTests/DataSourceTests.cs

Table Definitions need to be added after the ViewInfo elements to ensure serialization order of the server is respected.

Changes to ensure the table definitions are added last if the entropy information is missing.

---

src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/Utility/DirectoryHelper.cs
src/PAModel/Utility/FilePath.cs
src/PAModel/Utility/Utilities.cs
src/PAModelTests/FilePathTests.cs
src/PAModelTests/UtilityTests.cs

It is more likely to happen when with unicode characters, if this happens - and the full path length exceeds 260 limit, the filname would be truncated and it would be appended with a hash at the end (to avoid duplicates) while retaining the file extension.

#187 Truncating the file names if length exceeds MAX_PATH

---

src/PAModel/CanvasDocument.cs
src/PAModel/MsAppTest.cs
src/PASopa/Program.cs

This makes it easier for multiple clients to do the validation.

For SaveToSources, add a flag to test round tripping.

---

src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/Utility/DirectoryHelper.cs

The File.Exists was being passed the relative path which was not correct. Added a helped method to check for existance.

#240 - Changes to avoid creation of multiple .editorState.json files for TesttSuites

---

src/PAModel/ControlTemplates/ControlTemplateParser.cs
src/PAModel/Serializers/DefaultRuleHelper.cs
src/PAModel/SourceTransforms/DefaultValuesTransform.cs
src/PAModel/Themes/Theme.cs

While parsing control property fs the property is of string type and 
* not an expression
* not a localizedValue
* Not a uri
Then escape double quotes to retain string literal values

#194 : Changes to handle string type properties.

---

src/PAModel/CanvasDocument.cs

It was an instance property on CanvasDocument, but that class doesn't have a public ctor either.

Make version property static for easier discoverability by consumers.

---

src/PAModel/Utility/Utilities.cs
src/PAModelTests/UtilityTests.cs

Each EscapeChar (%) must be followed by two integer values if that is not the case then it is likely that the truncation left incomplete escapes. So making a fix to remove if the string ends with % or % followed by a single digit.

unrecognized hex char fix

---

src/PAModel/Serializers/SourceSerializer.cs

Fix for below error and similar types of errors
Error   PA3005: Validation error: Test Step Step22 references screen CheckBox,Toggle,Slider and Rating that is not present in the app

screens with excaped chars fail if test steps have references for it

---

src/PAModel/CanvasDocument.cs
src/PAModel/IR/UniqueIdRestorer.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/SourceTransforms/AppTestTransform.cs
src/PAModel/SourceTransforms/SourceTransformer.cs
src/PAModelTests/AppTestsTest.cs

Made the changes to read the screen names from app._screens rather than reading them from stateStore.
Also updated the logic to store screen index when entropy is deleted

#201 & #249 : Screen references in tests break if entropy or editorstates are deleted

---

src/PAModel/PAConvert/Yaml/YamlWriter.cs
src/PAModelTests/YamlTest.cs

Normalize \r style multiline properties correctly

---

src/PAModel/ControlTemplates/GlobalTemplates.cs
src/PAModel/ControlTemplates/commonStyleProperties.xml

This PR adds new properties being added to the common style properties in an internal PR to PowerApps Client, and also adds a check for the groupContainer in GlobalTemplates.cs. It's not clear to me _why_ the new changes in PAC are triggering the groupContainer to now be included, but we already have several work items to investigate the inconsistencies in the template versioning pipeline.

Add properties for the components tabstop fix

---

src/PAModel/EditorState/CombinedTemplateState.cs
src/PAModel/IR/IRStateHelpers.cs
src/PAModel/Schemas/DataComponentDefinitionJson.cs
src/PAModel/Schemas/adhoc/Control.cs

- Add AllowAccessToGlobals property on ComponentDefinitionInfoJson.
- Updates to IRStateHelper to use this property value.

Update to support addition of AllowAccessToGlobals property on component definition

---

src/PAModel/IR/IRStateHelpers.cs

Null check to prevent exceptions generated during yaml to .msapp conversion due to default dynamic properties generated.

Dynamic Property NullCheck

---

.vscode/extensions.json

Updating the recommended VS Code extensions since `ms-vscode.csharp` has been renamed to `ms-dotnettools.csharp`.

Fixing recommended VS Code extension

---

src/PAModel/CanvasDocument.cs

Problem:
Issue originally documented here: https://github.com/microsoft/PowerApps-Language-Tooling/issues/308 . When Properties.json is missing a table for a specific corresponding Data Source, it will cause this issue and refuse to unpack. However, it does not seem necessary for this validation error to be thrown because there is no roundtrip error otherwise.
Solution:
Remove the code that throws this validation error.

Issue 308: Removing Validation For Missing Data Source

---

src/PAModel/Schemas/ParameterSchema.cs

Unifying definitions with https://github.com/microsoft/Power-Fx/pull/215
Eventually, we'll update this tool to depend on PowerFx and pull the definition directly.

Bring ParameterSchema in line with PowerFx FormulaTypeSchema

---

src/PAModel/PAConvert/Yaml/YamlWriter.cs
src/PAModelTests/PublicSurfaceTests.cs

Making `YamlWriter` a public class so it can be utilized by other projects looking to conform to the Power App specific flavor of YAML.

Making YamlWriter a public class

---

src/PAModel/PAConvert/ErrorCode.cs

Appended the call stack to the error message when an internal error is thrown. This should now provide additional diagnostic information when such an error occurs.

Appended Call Stack to error message for Internal Error

---

src/PAModel/Entropy.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModelTests/DataSourceTests.cs

Problem : Noisy diffs because of connection instance ids
Solution:
- Extracting connection instance ids from connections.json to entropy.json from properties.json while unpacking
- Making sure to add it back to properties while repacking

Handling connection instance id and avoiding noisy diffs

---

src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj

- Setting GenerateAssemblyInfo property true for PALT package in .csproj results in details including assembly version linked to the build.
- Also updating the release note

Updating package details in PALT repo build

---

src/PAModel/Utility/FilePath.cs
src/PAModelTests/DataSourceTests.cs

Problem:
An exception is thrown when special characters are present in the filepath, during canvas unpack.
Solution:
When getting the filepath, escape out special characters.

Fixing exception from not handling special characters on canvas unpack

---

src/PAModel/Serializers/MsAppSerializer.cs

Solution: Remove roundtrip error code in #if !DEBUG tags, which adds an extra roundtrip error in Release mode.

Additional Roundtrip Logging in Release & Remove Double Roundtrip Printing

---

src/PAModel/SourceTransforms/AppTestTransform.cs
src/PAModel/SourceTransforms/ComponentInstanceTransform.cs
src/PAModel/SourceTransforms/GroupControlTransform.cs

Top errors are showing multiple results that seem like it is detecting a runtime error. This should not prevent pack\unpack from completing successfully. Should also evaluate other PA3005 to determine if there are other scenarios like this one which we can avoid.
Solution:
Remove exception throw for relevant errors.

PA3005: "Group control x state refers to non-existent child"

---

src/PAModel/Entropy.cs
src/PAModel/IR/IRStateHelpers.cs
src/PAModel/SourceTransforms/AppTestTransform.cs

Problem:
In some cases, when attempting to unpack an msapp using PALT, a TestStepsMetadata rule with empty InvariantScript property is being added after unpack during roundtrip causing a hash mismatch.
Solution:
Don't let a default TestStepsMetadate rule be added.
If one is added, throw an exception.

Empty TestStepsMetadata rule causing hash mismatch

---

docs/KnownIssues.md

Problem: 
- Function property InvariantScript value of controls with component definition set to false should be in sync with its component definition InvariantScript value.
Solution:
- Update the knownIssue doc

InvariantScript property of a control rule causing hash mismatch

---

src/PAModel/CanvasDocument.cs
src/PAModelTests/WriteTransformTests.cs

Resolving null reference exception in CanvasDocument.cs: RestoreAssetFilePaths()

Handling NullRefs: RestoreAssetFilePaths method

---

src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs

Handle null reference being thrown in EnsureFileDirExists:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.PowerPlatform.Formulas.Tools.DirectoryWriter.EnsureFileDirExists(String path)
```

Handle Null Reference thrown in EnsureFileDirExists

---

src/PAModel/Serializers/SourceSerializer.cs

**Exception log:**
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.PowerPlatform.Formulas.Tools.SourceSerializer.LoadSourceFiles(CanvasDocument app, DirectoryReader directory, Dictionary`2 templateDefaults, ErrorContainer errors)
at Microsoft.PowerPlatform.Formulas.Tools.SourceSerializer.LoadFromSource(String directory2, ErrorContainer errors)
at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.<>c__DisplayClass31_0.<LoadFromSources>b__0()
at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.Wrapper(Func`1 worker, ErrorContainer errors)
at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.LoadFromSources(String pathToSourceDirectory)
at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.SaveToSources(String …

Handling nullreference loadsourcefiles

---

src/PAModel/PAConvert/Yaml/YamlPocoSerializer.cs
src/PAModel/PAConvert/Yaml/YamlWriter.cs
src/PAModelTests/YamlTest.cs

Updating the YamlWriter class to append `=` for serialized values of type `int`, `double`, and `bool`. Without the `=` these will not be valid values in the Power App and have a formula warning when opening the App.
I believe this case was never encountered because `Visit` in PAWriterVisitor.cs turns everything to a string before writing the property:
https://github.com/microsoft/PowerApps-Language-Tooling/blob/e9c7885dbadfb467444e28ab4d15416fa032e28f/src/PAModel/PAConvert/PAWriterVisitor.cs#L109
The only other place these property types are being referenced directly is in YamlPocoSerializer, but this isn't used during the actual serialization of the Power App. I've updated it to be consistent with how it handles `string` types.
All test Apps continue to pass round-trip. Added some unit …

Updating YamlWriter for non-string types

---

src/PAModel/SourceTransforms/AppTestTransform.cs

Problem: With the new change to assign invalid screenname as null, dictionary with null key exception possible while reading it in beforeWrite()
Solution: handling cases when screenId is null, then avoiding this exception in ApptestTransform beforeWrite()
Validation: Roundtrips all test .msapps in test battery and in this repo without errors. Roundtrips validation successful for customer .msapp with this inconsistency.

handling test step screenId null case in ApptestTransform beforeWrite()

---

src/PAModel/SourceTransforms/AppTestTransform.cs
src/PAModelTests/RoundtripTests.cs

Resolving Null ref with ScreenId.
Also improving stresstest to include all test .msapps.
Validation: Roundtrips all test .msapps in test battery and in this repo without errors. 
Roundtrips validation successful for customer .msapp with this inconsistency.

Handling Null ref with ScreenId

---

src/PAModel/IR/IRStateHelpers.cs

Problem : AllowAccessToGlobals property should be in-sync across custom components, their instances and metadata . Currently there are instance where its not in-sync. Telemetry shows quite a lot of these errors reported.
Solution: Using ComponentDefinitionInfo AllowAccessToGlobals property value over ComponentManifest.AllowAccessToGlobals since ComponentDefinitionInfo values are source of truth
Validation: Roundtrips all test .msapps in test battery and in this repo without errors. Roundtrips validation successful for customer .msapp with this inconsistency.

Handling AllowAccessToGlobals property not in sync

---

.github/pull_request_template.md

- Update to Git files
There is no standardized form of PR documentation.
Create a PR template, so that all future PR's will start with the same generic format.
- Created a pull_request_template.md file (pr template)
- Compared to other PR Templates
- Talked to other team members

PALT PR Template

---

src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj

**Problem**: PALTVersion always showing as 0.0.0.0
**Solution**: Use the MinVer version (used for versioning in this repo) and set that as assemblyversion
**Validation**: Build and checked AssemblyInfo.cs generated, the version is updated

Making assembly version Up to date

---

src/PAModel/CanvasDocument.cs
src/PAModelTests/WriteTransformTests.cs

Null Reference and Argument Exceptions in RestoreAssetFilePaths()
Resolving these exceptions by handling duplicate keys and null references
Roundtrip validation on test .msapps and test battery

Handling CanvasDocument.RestoreAssetFilePaths() exceptions 

---

src/PAModel/PAConvert/Error.cs

No longer have filename as output when parsing error occurs.

Remove Filename Output when Parsing Error Occurs

---

src/PAModel/PAConvert/Parser/Parser.cs
src/PAModel/PAConvert/Yaml/YamlLexer.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModelTests/YamlTest.cs

Currently missing closing ' error gives no details on what identifier or cases cause this type of error.
Improving the missing closing quote error log with type details to debug the error better
- Added Unit tests
- Roundtrip testing the test .msapps
- Roundtrip testing the test battery .msapps

Improving the missing closing quote error log with line details

---

src/PAModel/CanvasDocument.cs
src/PAModelTests/WriteTransformTests.cs

Null Reference Exception in CanvasDocument.RestoreAssetFilePaths
Adding null checks and taking appropriate actions
-Added null check conditions in CanvasDocument.RestoreAssetFilePaths
Unit testing

handling null ref exception in RestoreAssetFilePaths

---

src/PAModel/CanvasDocument.cs
src/PAModelTests/ReadTransformTests.cs

Reproduced the same error in unit test 
Handle null resources in the StabilizeAssetFilePaths() while iterating through resourceJson.
Resource name null case handled too (might not be a valid scenario, but still an extra safe approach).
- Unit Testing

Handling NullRefException at CanvasDocument.<>c.<StabilizeAssetFilePaths>

---

src/PAModel/Serializers/SourceSerializer.cs

Error on unpack with unused Dataverse data source
-  Data source references with empty data sources were skipped.
- In some cases, data source can be empty, but the extension data is important and lost while unpacking causing the roundtrip to fail.
- Make sure LocalDatabaseRef contents are not lost while unpacking.
- Just save the LocalDatabaseRef as it is without skipping any content.
- Roundtrip validation on user app
- Unit testing
- Stress test on all test apps successful

Handling localdatabase references when unpacking

---

src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj
src/PAModelTests/PAModelTests.csproj

Component Governance - NewtonSoft.Json 13.0.1 High Severity
Upgrade NewtonSoft.Json version to 13.0.2
Roundtrip testing (existing roundtrip testing on test apps)

Updating Newtonsoft references to 13.0.2

---

src/PAModel/Entropy.cs
src/PAModelTests/EntropyTests.cs

Reported Issue : PA3001: Internal Error: Object Reference: GetResourcesJSONIndicesKey
"Error": **Unknown Error** 'Error   PA3001: Internal error. Object reference not set to an instance of an object.
Stack Trace:
at Microsoft.PowerPlatform.Formulas.Tools.Entropy.GetResourcesJsonIndicesKey(ResourceJson resource)
at Microsoft.PowerPlatform.Formulas.Tools.TranformResourceJson.PersistOrderingOfResourcesJsonEntries(CanvasDocument app)
at Microsoft.PowerPlatform.Formulas.Tools.CanvasDocument.ApplyAfterMsAppLoadTransforms(ErrorContainer errors)
at Microsoft.PowerPlatform.Formulas.Tools.MsAppSerializer.SaveAsMsApp(CanvasDocument app, String fullpathToMsApp, ErrorContainer errors, Boolean isValidation)',
"Count": 258
Handle resource null case before Entropy.GetResourcesJsonIndicesKey()
Roundtrip …

Handling object reference not set GetResourcesJSONIndicesKey

---

targets/Program.cs

Folder with spaces causes Build.cmd to fail
Put quotation marks around directory names, in case the directory name contains spaces. This tells the compiler that this is only one argument, despite containing spaces

Make build.cmd work in directories that have spaces in their name

---

src/PAModel/Entropy.cs
src/PAModel/IR/IRStateHelpers.cs
src/PAModelTests/EntropyTests.cs

- Different control instances could have different template data even if they appear to follow same template.
- Like version, DynamicControlDefinitionJSON etc could be different.
``` 
Eg: Control Instance 1 -> pcftemplate1 -> DynamicControlDefinitionJson1
Control Instance 2 -> pcftemplate1 -> DynamicControlDefinitionJson2
```
- This causes roundtrip errors like below
- Make use of entropy data and create a new dictionary to store/retrieve PCF template data
- Store PCFtemplate separately while unpacking >>> ` IRStateHelpers.SplitIRAndState()`
- Retrieve the stored PCFtemplate data while packing >>> `IRStateHelpers.CombineIRAndState()`
- This will avoid such roundtrip errors
- UnitTesting

Handling PCF template data separately for each PCF control instance

---

src/PAModel/IR/IRStateHelpers.cs
src/PAModelTests/EntropyTests.cs

The way PCF templates are stored was changed so that each control's specific template is stored in a new field in `Entropy.json`. This was done to resolve an issue where differing versions of the same control type would incorrectly use the same template.
Since `Entropy.json` should technically only contain fields which are optional, this introduced an issue where an empty `Entropy.json` would mean that the entire PCF template would be missing when restoring the `.msapp`. This change will keep a copy of the PCF template in the template store as well, as a fall back in case it cannot be found on a per-PCF control basis.
This is challenging to validate, because it isn't easily caught in round-trip testing, as it involves the `Entropy.json` file being modified between the unpack and pack. …

Fix PCF template storage

---

README.md

Previous badge for status of the build:
Which links to: https://github.com/badges/shields/issues/8671
Resolved badge:

Fixing build badge in README

---

.github/workflows/CI.yml
global.json

Unable to build with supported versions of DotNet SDK
Update from 3.0 to 6.0 (LTS)
Supported versions are 6.0, 7.0, 8.0
https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
Successful build and run

Updated dotnet SDK to 6.0

---

README.md
azure-pipelines.yml
src/PAModel/Schemas/PcfControls/PcfControl.cs

Azure Pipeline uses out of support SDK
Update to dot net SDK 6.0

Update Azure Pipeline to Dotnet SDK 6.0

---

src/PAModel/PAConvert/Yaml/YamlLexer.cs
src/PAModelTests/PAModelTests.csproj
src/PAModelTests/YamlTest.cs

```
Error: Error   PA3013: Property Value Changed: TopParent.Children[0].Children[1].Rules[2].InvariantScript
Error   PA3011: Roundtrip validation on unpack failed.
You have found a bug; this is not a specific bug, rather an indicator that some bug has been encountered.
Please open an issue and log the entirety of this error log at https://github.com/microsoft/PowerApps-Language-Tooling
```
While validating we use normalized line endings but YamlLexer has Windows style endings hardcoded
Updated unit tests to validate

Fixed multiline msapp pack errors

---

src/PAModel/Serializers/SourceSerializer.cs
src/PAModel/Serializers/TransformLogo.cs

We don't want a missing logo file to throw an error, we'd like it to roundtrip so as not to block the user from packing the app.
Remove the error that throws, and make sure the FileName is not null.
- Self validation

Fix Missing Logo File Throwing an Error

---

src/PAModel/Schemas/HeaderJson.cs

Adding new properties to Header.json fails round trips. 
Add [JsonExtensionData] member. 
Add [JsonExtensionData] member. 
Tested against PA Client change

Add JsonExtensionData member to HeaderJson

---

src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj
src/PASopa/PASopa.csproj

Net Core 3.1 is no longer supported
Converted to Net 6.0 LTS

Net Core 3.1 is no longer supported. Converted to Net 6.0 LTS

---

src/Microsoft.PowerPlatform.PowerApps.Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/BuiltInTemplatesUris.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/Button.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/Control.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/ControlProperty.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/CustomControl.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/FirstClassAttribute.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/Label.cs
src/Microsoft.PowerPlatform.PowerApps.Persistence/Models/Screen.cs
src/PASopa.sln

Adding first version of POCO classes that will be used for our MSAPPs

added new Microsoft.PowerPlatform.PowerApps.Persistence project

---

src/Persistence.Tests/Extensions/StringExtensionsTest.cs
src/Persistence/Extensions/StringExtensions.cs

with .NET 8 we could gain a little bit more by passing params by ref

micro optimization

---

.editorconfig
.version/PipelineAssemblyInfo.cs
src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/Yaml/RoundTripTests.cs
src/Persistence.Tests/Yaml/ZIndexOrderingTests.cs
src/Persistence.Tests/_TestData/AppsWithYaml/HelloWorld.msapp/Src/HelloScreen.fx.yaml
src/Persistence.Tests/_TestData/ValidYaml/Control-with-custom-template.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen-with-controls-as-temples.fx.yaml
src/Persistence.Tests/_TestData/ValidYaml/Screen-with-controls.fx.yaml
src/Persistence.Tests/_TestData/ValidYaml/ZIndexOrdering/Screen-with-sorted-children.fx.yaml
src/Persistence/Collections/ControlPropertiesCollection.cs
src/Persistence/Models/Control.cs
src/Persistence/Yaml/PropertyNames.cs
src/Persistence/Yaml/YamlSerializationFactory.cs

When serializing, child controls will be sorted by their ZIndex property and the property itself will be omitted from the yaml output.  When deserializing, the ZIndex property will be added to each control based on the order found in the yaml array.

ZIndex handling - Controls should be serialized in ZIndex order, and the property itself should be ommited from the YAML

---

samples/Test.AppWriter/ExampleAppGenerator.cs
samples/Test.AppWriter/Program.cs

- **Changed the expected format for the --controls argument to the Test.AppWriter commandline app, now it expects only a list of templates and will auto-generate placeholder names**

Updated argument format for Controls in AppWriter

---

src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/_TestData/ValidYaml/App-with-settings.pa.yaml
src/Persistence/Models/App.cs
src/Persistence/Models/Settings.cs

For single-yaml load, we'll need a way to represent some app characteristics, like app name and layout. This is not yet intended for the load/save path, however, it should be able to converge long term.

Add place for Settings as a child of App

---

src/Persistence.Tests/_TestData/InvalidYaml/screen-with-not-valid-control.pa.yaml
src/Persistence/Yaml/ControlObjectFactory.cs
src/Persistence/Yaml/ControlTypeInspector.cs

Expected error message:
Property 'NoValidControl' not found on type 'Microsoft.PowerPlatform.PowerApps.Persistence.Models.Control'.

Improved error reporting for invalid properties

---

src/Persistence.Tests/Yaml/DeserializerInvalidTests.cs
src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence.Tests/Yaml/RoundTripTests.cs
src/Persistence/MsApp/IMsappArchive.cs
src/Persistence/MsApp/MsappArchive.cs
src/Persistence/Yaml/IYamlDeserializer.cs
src/Persistence/Yaml/IYamlSerializationFactory.cs
src/Persistence/Yaml/IYamlSerializer.cs
src/Persistence/Yaml/YamlDeserializer.cs
src/Persistence/Yaml/YamlSerializationFactory.cs
src/Persistence/Yaml/YamlSerializer.cs

Encapsulate the YamlDotNet serializer and deserializer, giving us an extension point for Control specific conversions

Encapsulate the YamlDotNet serializer and deserializer

---

.editorconfig
nuget.config
src/Directory.Build.props

- In some developer configurations, nuget is not able to restore packages due to custom user scoped nuget configuration.
- When developing in VS IDE, builds often fail due to style rules failing. This hinders speed of development when trying to just get some things done.
- Added nuget.config to the root of the repo which states to use nuget.org feed.
- IDE#### rules no longer error out, but are set as warnings.
- modified the msbuild properties which were forcing all analysis and style rules to cause errors, thus build failures. These now only get set when NOT in a VS IDE.

fix local build issues

---

src/Persistence.Tests/Extensions/PersistenceFluentExtensions.cs
src/Persistence.Tests/PaYaml/PaYamlSerializerTests.cs
src/Persistence.Tests/PaYaml/Serialization/PFxExpressionYamlConverterTests.cs
src/Persistence.Tests/Persistence.Tests.csproj
src/Persistence.Tests/TestBase.cs
src/Persistence/GlobalSuppressions.cs
src/Persistence/PaYaml/Models/PowerFx/PFxDataType.cs
src/Persistence/PaYaml/Models/PowerFx/PFxExpressionYaml.cs
src/Persistence/PaYaml/Models/PowerFx/PFxFunctionParameter.cs
src/Persistence/PaYaml/Models/SchemaV2_2/AppInstance.cs
src/Persistence/PaYaml/Models/SchemaV2_2/ComponentDefinition.cs
src/Persistence/PaYaml/Models/SchemaV2_2/ControlInstance.cs
src/Persistence/PaYaml/Models/SchemaV2_2/ModelsExtensions.cs
src/Persistence/PaYaml/Models/SchemaV2_2/PaFileRoot.cs
src/Persistence/PaYaml/Models/SchemaV2_2/SchemaKeywords.cs
src/Persistence/PaYaml/Models/SchemaV2_2/ScreenInstance.cs
src/Persistence/PaYaml/PaYamlDotNetExtensions.cs
src/Persistence/PaYaml/PaYamlSerializationException.cs
src/Persistence/PaYaml/PaYamlSerializer.cs
src/Persistence/PaYaml/PaYamlSerializerOptions.cs
src/Persistence/PaYaml/Serialization/PFxExpressionYamlConverter.cs
src/Persistence/PaYaml/Serialization/PFxExpressionYamlFormattingOptions.cs
src/Persistence/Yaml/YamlSerializationFactory.cs

Simple implementation of Yaml Schema v2.2 OM (as defined in XR and schema file already in master).
Added a new OM and namespace for representing just the Yaml schema for *.pa.yaml files.
Added unit tests and also verify the Example pa.yaml files written according to the schema.
NOTE: This OM is an initial implementation to enable the start of writing the transformation from the existing OM (aka v2.1) to v2.2.

Yaml Schema v2.2 OM - initial implementation

---

src/Persistence.Tests/Yaml/DeserializerValidTests.cs
src/Persistence/Models/Control.cs
src/Persistence/Templates/BuiltInTemplates.cs

Children of group containers are ordered in the tree view in reverse of zindex order. This update changes the serialize/deserialize logic so that the serialized order matches the tree view order.

Reverse ZIndex ordering for children of group containers

---

src/Persistence.Tests/Model/CustomPropertyTests.cs
src/Persistence.Tests/_TestData/ValidYaml-CI/Components/CustomProperty1.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml-CI/Components/CustomProperty2.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Components/CustomProperty1.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/Components/CustomProperty2.pa.yaml
src/Persistence/Models/CustomProperty.cs

The category field on Custom Properties can be inferred from the property type:
1. Data -> Data
2. Action ->Behavior
3. Event -> Behavior
4. Function -> Data

removed unnecessary category field

---

src/Persistence/Templates/ControlTemplate.cs

The current OM doesn't allow for control template to indicate whether it represents a custom component or a Pcf control.
Yaml serialization needs to be able to emit the identifiers used to uniquely identify a control instance.
Added some new properties to `ControlTemplate`.
- Added properties to `ControlTemplate`: `IsCustomComponent`, `ComponentInfo`, `IsPcfControlTemplate`
Not used atm, but is a placeholder for getting the data from the Document Server.

Update `ControlTemplate` to indicate whether it's a Component or Pcf control template

---

src/Persistence/Models/Component.cs
src/Persistence/Models/Control.cs
src/Persistence/Models/CustomProperty.cs
src/Persistence/Yaml/CustomPropertiesCollectionConverter.cs

`Control`'s `[OnSerializing]` and `[OnDeserialized]` hooks are redundant, as that logic is also in `ControlFormatter.BeforeSerialize()` and `ControlFormatter.AfterDeserialize()`, which is called by the [`ControlConverter`](https://github.com/microsoft/PowerApps-Language-Tooling/blob/ecd502f229b7211ce4d70c313a42e6d272c9ce03/src/Persistence/Yaml/ControlConverter.cs)
`Component`'s `[OnDeserialized]` logic is likewise performed in [`CustomPropertiesCollectionConverter`](https://github.com/microsoft/PowerApps-Tooling/blob/ecd502f229b7211ce4d70c313a42e6d272c9ce03/src/Persistence/Yaml/CustomPropertiesCollectionConverter.cs)
and this PR also moves `CustomProperty`'s `[OnDeserialized]` logic to the same
For future work converting this current top-level OM to the new one, the same logic in …

Remove [OnDeserialized] and [OnSerializing] hooks

---

.editorconfig
samples/MauiMsApp/CreatePage.xaml.cs
samples/MauiMsApp/MainPage.xaml.cs
samples/Test.AppWriter/InputProcessor.cs
src/PAModel/ControlTemplates/ControlTemplateParser.cs
src/PAModel/MsAppTest.cs
src/PAModel/PAConvert/Parser/Parser.cs
src/PAModel/PAConvert/Yaml/YamlLexer.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/Serializers/SourceSerializer.cs
src/PAModelTests/RoundtripTests.cs
src/PASopa/Program.cs
targets/Program.cs

For code quality, maintenance, and usage this PR enables diagnostic rules related to usage of IDisposable objects and exceptions.
Update .editorconfig rules and fixed or suppressed existing violations.

Enable rules for IDisposable and exceptions

---

src/Persistence.Tests/Extensions/PersistenceFluentExtensions.cs

`KeyNotFoundException` is thrown in `PersistenceFluentExtensions` when a key is missing.
Changed the implementation to enable usage of the TryGet pattern APIs so it doesn't throw.

fix `KeyNotFoundException` in `PersistenceFluentExtensions`

---

src/Persistence.Tests/PaYaml/Serialization/NamedObjectSequenceSerializationTests.cs
src/Persistence.Tests/PaYaml/Serialization/PFxExpressionYamlConverterTests.cs
src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence.Tests/PaYaml/Serialization/SerializationTestBase.cs
src/Persistence/PaYaml/Models/INamedObject.cs
src/Persistence/PaYaml/Models/NamedObject.cs
src/Persistence/PaYaml/Models/YamlLocation.cs
src/Persistence/PaYaml/Serialization/NamedObjectYamlConverter.cs
src/Persistence/PaYaml/Serialization/PaSerializationContext.cs
src/Persistence/PaYaml/Serialization/PaYamlSerializerOptions.cs
src/Persistence/PaYaml/Serialization/YamlConverterOfT.cs
src/Persistence/PaYaml/Serialization/YamlDotNetExtensions.cs
src/Persistence/PaYaml/Serialization/YamlSerializer.cs

This PR solves issue of "Pa" repeating three times.  Microsoft.PowerPlatform.**PowerApps**.Persistence.**Pa**Yaml.Serialization.**Pa**YamlSerializer

Removed "Pa" prefix where it is not necessary

---

src/PASopa.sln
src/YAMLValidator/InputProcessor.cs
src/YAMLValidator/Program.cs
src/YAMLValidator/YAMLValidator.csproj

N/A
N/A
- Adds the initial CLI scaffolding and verification for the YAML validator, which for now, only verifies file extemsions and validates the files and directories exists.
- The added command includes the ```validate``` CLI command, flags include:
- required ```--path``` a path to a .yaml or folder of .yaml files
- optional ```--schema``` a path to a local schema .json file, or a default one if it is not passed in.
- 
- For now only manual tests were done to verify input filepaths, these tests included
1. No parameters passed to cli
2. Validate command without parameters
3. Validate command with an invalid and valid file path
4. Validate command with an invalid and valid folder path
5. Path option input validation to check at least 1 .yaml file exists in a folder
6. Path option input …

CLI scaffolding for YAMLValidator

---

src/Persistence.Tests/Yaml/ValidSerializerTests.cs
src/Persistence.Tests/_TestData/ValidYaml-CI/ZIndexOrdering/with-addpropertiestoparents-control.pa.yaml
src/Persistence.Tests/_TestData/ValidYaml/ZIndexOrdering/with-addpropertiestoparents-control.pa.yaml
src/Persistence/Yaml/ControlFormatter.cs

Currently when we vie code for gallery, the ZIndex is being serialized at the parent level. Changes here are the skip the ZIndex
Add a check to skip Zindex
- Log what was changed
- Log what was changed
- Log what was changed

Skip ZIndex from being serialized.

---

.editorconfig
.vscode/settings.json
src/Directory.Build.props
src/PASopa.sln
src/Persistence.Tests/.editorconfig

This PR re-fixes issues in the inner dev loop which I'd previously fixed but have been broken again. All of these changes have been fixed at one point, hopefully it'll stick this time.
- Turned off TreatWarningsAsErrors in VS IDE to speed up inner-dev-loop.
building locally in VS IDE causes warnings to be treated as Errors. This negatively impacts the inner dev loop experience and causes slower iterative development.
- fix settings.json so PaYamlV3 files use the correct schema file
*.pa.yaml files under the PaYamlV3 folders in the repo no longer work with the schemas as they did before.
- Turned some code analysis rules from Error to Warning to improve inner dev-loop

Fix broken build, and inner dev-loop configurations

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/Persistence/PaYaml/Models/ISupportsIsEmpty.cs
src/Persistence/PaYaml/Models/SchemaV3/ControlInstance.cs
src/Persistence/PaYaml/Models/SchemaV3/InstanceCreationParameters.cs
src/Persistence/PaYaml/Models/SchemaV3/ScreenInstance.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/Screens/FormsScreen2.pa.yaml
src/schemas-tests/pa-yaml/v3.0/Examples/Src/Screens/Screen1.pa.yaml
src/schemas-tests/pa-yaml/v3.0/FullSchemaUses/Screens-general-controls.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

In order to support the potential 'editor-only-state' that's currently required for certain scenario, this PR adds a `CreationParameters` property to screen and control instance objects in the PaYamlV3 OM.

Add `CreationParameters` property to PaYamlV3 OM

---

src/YamlValidator/ValidatorResults.cs

- In the current validation output there is an edge case with returning output on an Invalid Schema.
- The schema structure requires that at the root of the yaml we either have a single control or an array of controls (using a OneOf json-schema statement)
- In a valid schema, a single evaluation path being true (object or array of objects) will make the entire schema true
- In an invalid schema, both evaluation paths will be false. Suppose we wanted to trace an error; we would have to go down both evaluation paths in the evaluation tree (one of which would always evaluate to false even if the schema was valid). 
- This additional useless information is output on the console to the user and is confusing/uninformative. This pr removes the evaluation path which contains useless information. …

Clean yaml validator false positive output

---

src/Directory.Build.props
src/PAModel/Checksum/ChecksumMaker.cs
src/PAModel/IsExternalInit.cs
src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj
src/PAModel/PAConvert/Parser/CharacterUtils.cs
src/PAModel/PAConvert/Yaml/YamlLexer.cs
src/PAModel/Serializers/MsAppSerializer.cs
src/PAModel/packages.lock.json
src/Persistence.Tests/Persistence.Tests.csproj
src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj

In commit [1c9b22c](https://github.com/microsoft/PowerApps-Tooling/commit/1c9b22cef15b0da9d8afbdb57aebaac3252807ed) back in Dec 2023, all projects in the repo were set to use the same TargetFramework, all sourced from a single shared file.
This accidentally effected the Formulas.Tooling lib, which needs to remain on netstandard2.0 for use in both .NET and .NET Framework versions of PAC CLI.
This PR switches that library back to netstandard2.0, and reverts a few changes since that point for new syntax net8.0 which is not available to netstandard2.0.

Return Formulas.Tools to netstandard2.0

---

src/PAModel/Microsoft.PowerPlatform.Formulas.Tools.csproj

The goal of PR #684 was to fix the Microsoft.PowerPlatform.Formulas.Tools nuget package by returning a netstandard2.0 version for consumption within full .NET Framework projects such as the net48 version of PAC CLI.  
While that resulted in a nuget package with both net8.0 and netstandard2.0 folders, the actual DLLs in both of those folders were in fact the net8.0 version, as I was not overriding a few values coming from the parent Directory.Build.props file.

Fix framework multitargeting

---

src/YamlValidator/YamlLoader.cs

- File names are stored in a dictionary so that they can be output in the console
- Two of the same file names in different folders cause an error when recursively traversing the folders due to a repeated key (was found when traversing the Persistence.Tests Valid-CI test data folder)
The way file names are stored in a dictionary and output. Specifically, use the relative path of a file as the name of the file instead of just the filename.
- Re-ran unit tests, manual validation

Yaml Validator Bug: same file names in different folder cause error

---

src/YamlValidator/SchemaLoader.cs
src/YamlValidator/ValidatorError.cs
src/YamlValidator/YamlValidatorLibraryException.cs

- Added custom exception to handle expected exceptions from YamlValidator. This will be used in PAC CLI to indicate the error came from the YamlValidator library if the schema couldn't be loaded from the assembly when the IValidatorFactory is asked to create a new validator.
- Also changed the printing format of Validator Results (inconsequential)
Custom exception to be used by library callers to handle errors
- Log what was changed
- Log what was changed
- Log what was changed

Add custom exception for errors from Yaml Validator Library

---

.editorconfig
src/Persistence/Collections/ControlPropertiesCollection.cs
src/Persistence/Collections/CustomPropertiesCollection.cs
src/Persistence/Collections/CustomPropertyParametersCollection.cs
src/Persistence/Extensions/YamlExtensions.cs
src/Persistence/PaYaml/Models/NamedObjectMapping.cs
src/Persistence/PaYaml/Models/NamedObjectSequence.cs

Using `build ci` at githash 5b4aa54 gives 'error IDE0036: Modifiers are not ordered'
/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Collections/ControlPropertiesCollection.cs(10,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps.Persistence.csproj] /Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Collections/CustomPropertiesCollection.cs(10,5): error IDE0036: Modifiers are not ordered (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0036) [/Users/jb/src/github.com/microsoft/PowerApps-Tooling/src/Persistence/Microsoft.PowerPlatform.PowerApps. …

prevent 'error IDE0036: Modifiers are not ordered'

---

src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence/PaYaml/Models/SchemaV3/DataSourceInstance.cs
src/Persistence/PaYaml/Models/SchemaV3/PaModule.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/DataSources/DataSources1.pa.yaml

YAML V3 schema for Data Sources
1. The initial version of this schema will define the necessary structure for Dataverse data sources within the current environment.
2. The `DataSourceInstance ` type is a flattened structure that incorporates all potential properties of a YAML data source, with only one required property: `Type`.
3. The `Type `property is mandatory and serves to identify the specific polymorphic type. Validation of this property will occur during parsing.
Below is a sample v3 pa yaml with dataverse datasources from current environment.
- Introduced a top-level node specifically for Data Sources.
- Defined distinct types for various Data Source properties.
- Implemented unit tests to validate the Data Source schema.
- Local debugging/testing

V3 YAML schema for Data Sources

---

src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence.Tests/_TestData/InvalidYaml-CI/duplicate-control-in-sequence.pa.yaml
src/Persistence/PaYaml/Serialization/PaYamlSerializer.cs
src/Persistence/PersistenceErrorCode.cs

Added specific error code and detection for duplicate names in yaml sequence.
Example:
```
- MyControl:
Control: Label
- MyControl:
Control: Label
```

added detection for duplicate names in yaml sequence

---

src/Persistence/PaYaml/Models/SchemaV3/DataSourceInstance.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/DataSources/DataSources1.pa.yaml

Updating the YAML v3 schema for DataSource according to below [tech design](https://microsoft.sharepoint-df.com/:fl:/g/contentstorage/CSP_fbfb0a53-e4e1-4407-8b36-716d46cc0d5f/EYaglxwWl0FLiP_NCzeYtJ4BKak3hM7gZMwd0rxfUa4CVg?e=HeWS9L&nav=cz0lMkZjb250ZW50c3RvcmFnZSUyRkNTUF9mYmZiMGE1My1lNGUxLTQ0MDctOGIzNi03MTZkNDZjYzBkNWYmZD1iJTIxVXdyNy0tSGtCMFNMTm5GdFJzd05YeS1obEdfdlNoZElyU200RG5YejJMcVpLTE5yMVZmRFJJVFV3U2dHNjBxYyZmPTAxRjNWVERBNEdVQ0xSWUZVWElGRllSNzZOQk0zWlJORTYmYz0lMkYmYT1Mb29wQXBwJnA9JTQwZmx1aWR4JTJGbG9vcC1wYWdlLWNvbnRhaW5lciZ4PSU3QiUyMnclMjIlM0ElMjJUMFJUVUh4dGFXTnliM052Wm5RdWMyaGhjbVZ3YjJsdWRDMWtaaTVqYjIxOFlpRlZkM0kzTFMxSWEwSXdVMHhPYmtaMFVuTjNUbGg1TFdoc1IxOTJVMmhrU1hKVGJUUkVibGg2TWt4eFdrdE1Ubkl4Vm1aRVVrbFVWWGRUWjBjMk1IRmpmREF4UmpOV1ZFUkJNMU5LV2xJM05FSkxNelpHUWt4UVZETk1UamRMTkZCRU1sayUzRCUyM …

Update schema of DataSource in v3 YAML

---

src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence/PaYaml/Serialization/PaYamlSerializer.cs
src/Persistence/PaYaml/Serialization/YamlSequenceTesterConverter.cs

Added a new `CheckIsSequence` method to detect if a yaml fragment is a sequence. It internally creates a new YamlDotNet deserializer that uses the custom type converter `YamlSequenceTesterConverter`.
This converter will simply check if the YAML fragment starts with the `SequenceStart` event and ends with `SequenceEnd`.
The following benchmark shows the results of a few deserialization methods:
- Direct deserialization to `IEnumerable<object>` using a basic YamlDotNet deserializer
- Direct deserialization to `object[]` using a basic YamlDotNet deserializer
- Direct deserialization to `Dictionary<string,object>[]` using a basic YamlDotNet deserializer
- the newly introduced `CheckIsSequence` method
- deserialization using the v2 deserializer
- deserialization using the v3 deserializer …

added method to detect if a yaml fragment is a sequence

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/Persistence/PaYaml/Models/SchemaV3/ControlInstance.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/Screens/FormsScreen2.pa.yaml
src/schemas-tests/pa-yaml/v3.0/FullSchemaUses/Screens-general-controls.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

For form controls, layout can be edited by makers to change the visual layout of the control. Hence, we need to serialize it with YAML schema
Add layout to V3 schema
Adds layout to V3 schema

Add layout to V3 schema

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

There is a small error in the regex for Components in the YAML V3 Schema
I have updated the regex removing an unnecessary character that led to validation failures
- Removed a '*' at the end of the Component regex in v3 pa.schema

Fixing regex for components in v3 schema

---

src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence/PaYaml/Models/SchemaV3/ComponentDefinition.cs

To normalize the output yaml for component properties, by convention, "differentiator keywords" are generally emitted first. While not a technical requirement, it allows for easier to read code and is consistent with similar patterns in the OM.
Added unit test that verifies the order of yaml keywords.

Reorder component property keywords so the `PropertyKind` is first

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/Persistence.Tests/PaYaml/Serialization/PFxExpressionYamlConverterTests.cs
src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence/PaYaml/Models/PowerFx/PFxFunctionParameter.cs
src/Persistence/PaYaml/Models/SchemaV3/ComponentDefinition.cs
src/Persistence/PaYaml/Serialization/PFxExpressionYamlConverter.cs
src/Persistence/PaYaml/Serialization/PFxExpressionYamlFormattingOptions.cs
src/schemas-tests/pa-yaml/v3.0/Examples/AmbiguousComponentNames.pa.yaml
src/schemas-tests/pa-yaml/v3.0/Examples/Src/Components/MyHeaderComponent.pa.yaml
src/schemas-tests/pa-yaml/v3.0/FullSchemaUses/ComponentDefinitions.pa.yaml
src/schemas-tests/pa-yaml/v3.0/FullSchemaUses/Screens-with-components.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

- `PFxFunctionParameter` now supports `Default` keyword being a PFx expression.
- `ComponentDefinition.DefinitionType` added with enum `ComponentDefinitionType`, to differentiate between Canvas and Command components.
- Added tests for `PFxExpressionYamlConverter` to show the handling of trailing whitespace. Turns out YamlDotNet cannot support us forcing these to use Literal block syntax.
- Adapted to add quotes around values which end with the tab character.
- Use ImmutableArray instead of IReadOnlyList for options.
- Updated `pa.schema.yaml` and added more tests.

PaYamlV3 OM schema & PFxExpressionYamlConverter changes

---

src/Persistence/PaYaml/Models/NamedObjectCollectionExtensions.cs
src/Persistence/PaYaml/Models/SchemaV3/ComponentDefinition.cs
src/Persistence/PaYaml/Models/SchemaV3/ControlInstance.cs
src/Persistence/PaYaml/Models/SchemaV3/DataSourceInstance.cs
src/Persistence/PaYaml/Models/SchemaV3/PaModule.cs
src/Persistence/PaYaml/Models/SchemaV3/PaYamlPropertyDataType.cs

In order to allow the PaYamlParser to detect when a keyword is missing, we need to ensure value types are allowed to be set to null. Also, to reduce memory footprint, collections are allowed to be null too.

Fix OM to allow detection of missing keywords

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/Persistence/PaYaml/Models/SchemaV3/ControlInstance.cs
src/schemas-tests/pa-yaml/v3.0/FullSchemaUses/Screens-general-controls.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

For dataCard and typedDataCard instances, we must enable setting a `MetadataKey` which will be mapped to a `metadataId` in the control template's variant so that changing layouts will work.
- Added unit tests coverage.

Add `MetadataKey` keyword to control instances

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/Persistence/PaYaml/Models/SchemaV3/ScreenInstance.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/Screens/Screen1.pa.yaml
src/schemas-tests/pa-yaml/v3.0/FullSchemaUses/Screens-general-controls.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

This PR introduces the DisplayOrder field to the Screen schema, allowing the display order of a screen in PowerApps to be persisted. The field is defined as a nullable integer. Additionally, the PR updates the relevant schema definitions and test cases.

Add DisplayOrder Field to Screen Schema

---

schemas/pa-yaml/v3.0/pa.schema.yaml
src/Persistence.Tests/PaYaml/Serialization/PaYamlSerializerTests.cs
src/Persistence/PaYaml/Models/SchemaV3/EditorStateInstance.cs
src/Persistence/PaYaml/Models/SchemaV3/PaModule.cs
src/schemas-tests/pa-yaml/v3.0/Examples/Src/_EditorState.pa.yaml
src/schemas-tests/pa-yaml/v3.0/FullSchemaUses/EditorStateSample.pa.yaml
src/schemas/pa-yaml/v3.0/pa.schema.yaml

This PR adds support for the `EditorState` top-level property to the PA YAML schema files. EditorState provides editor-specific metadata that doesn't affect app functionality but improves the editing experience by preserving UI element ordering.
- Added `EditorState` as a top-level property in the schema
- Created `EditorState-instance` definition with two properties:
- `ScreensOrder`: An ordered array of screen names for editor display
- `ComponentDefinitionsOrder`: An ordered array of component definition names for editor display
- Schema changes align with existing C# model classes (`PaModule` and `EditorStateInstance`)
- Applied changes to both schema locations:
- `/src/schemas/pa-yaml/v3.0/pa.schema.yaml`
- `/schemas/pa-yaml/v3.0/pa.schema.yaml`
- Enables proper schema validation for …

Add EditorState to PA YAML schema to support editor UI ordering

---

src/Persistence.Tests/PaYaml/Serialization/PFxExpressionYamlConverterTests.cs

Writing Unit Test for LoadingPage.OnVisible in shows as escaped string in codeview
Added unit test method to make this issue a known bug. Verified the code is functioning as is seen in UI.
Added a unit test method to class PFxExpressionYamlConverterTests.cs
Unit Test Validation

Unit Test for UI Bug YAML De-Serialization Not Working As Expected

---

src/YamlValidator/Microsoft.PowerPlatform.PowerApps.YamlValidator.csproj
targets/targets.csproj

Updating System.Text.Json version for CVE-2024-43485, and updating the build project's .NET version

Updating dependency and build project framework versions

---

src/Persistence.Tests/PaYaml/Serialization/PFxExpressionYamlConverterTests.cs
src/Persistence/PaYaml/Serialization/PFxExpressionYamlConverter.cs

Force literal block for Unicode characters to preserve them without escaping
The Unicode characters were being escaped.
Force literal block for Unicode characters to preserve them without escaping

Force literal block for Unicode characters to preserve them without escaping
